In [17]:
%load_ext autoreload
%autoreload 2
from baum_welch import *

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [33]:
T = 5000
N = 100

A = np.array([[0.1933, 0.8067], [0.6167, 0.3833]])
B = np.array([[0.4134, 0.5866], [0.1002, 0.8998]])
pi = np.array([[2/3],[1/3]])

f = open("sequence.txt", "r")
teoretical_observations = []
temp = []
while True:
    char = f.read(1)
    if not char:
        break
    if char != ',' and char != '\n':
        temp.append(int(char)-1)
    if len(temp) == N:
        teoretical_observations.append(temp)
        temp = []
O = np.array(teoretical_observations)

A, B, pi = fit(A, B, O, K=2, NUM_ITER=1000, pi=pi)
print(A)
print(B)

[[0.31351107 0.68648893]
 [0.62435227 0.37564773]]
[[0.48180196 0.51819804]
 [0.44467416 0.55532584]]


In [32]:
A, B, pi = fit(A, B, O, 2, NUM_ITER=2000, pi=pi)
print(A)
print(B)

[[0.83264244 0.16735756]
 [0.29151724 0.70848276]]
[[0.9878546  0.0121454 ]
 [0.66199096 0.33800904]]
